const INITIAL_PIECE_OFFSET = 8;
const DARK_BOX_COLOR = "#18BC9C";
const LIGHT_BOX_COLOR = "#FFF8DC"
const MAX_ENTRIES_IN_LEADER_BOARD = 20;
const LOCAL_STORAGE_LEADER_BOARD_DATA = 'leaderBoardData';

export {INITIAL_PIECE_OFFSET, DARK_BOX_COLOR, LIGHT_BOX_COLOR, MAX_ENTRIES_IN_LEADER_BOARD, LOCAL_STORAGE_LEADER_BOARD_DATA};